"""
Empirical studies evaluating FinLens's core claims.

Profiles are generated by sampling plausible input ranges; outcomes are
then measured by simulation. Profiles are never constructed to produce a
particular result -- the input/outcome relationship is discovered, not planted.
"""

import numpy as np

from src.profile import FinancialProfile, LoanScenario, SimulationAssumptions
from src.engine import evaluate_scenario
from src.simulation import simulate_scenario
from src.scoring import borrowing_stress_score


def generate_population(n: int, seed: int = 7) -> list[dict]:
    """
    Sample n plausible household + loan combinations.

    Ranges are chosen to span realistic Indian middle-income situations
    without targeting any particular risk outcome.
    """
    rng = np.random.default_rng(seed)

    population = []
    for i in range(n):
        income = float(rng.uniform(35_000, 150_000))
        expense_ratio = float(rng.uniform(0.25, 0.55))       # expenses as share of income
        expenses = income * expense_ratio
        existing_emi = float(rng.uniform(0, 0.15) * income)
        savings_months = float(rng.uniform(0.5, 18))          # months of expenses saved
        savings = expenses * savings_months

        principal = float(rng.uniform(200_000, 1_500_000))
        rate = float(rng.uniform(9, 16))
        tenure = int(rng.integers(2, 8))

        # Volatility varies across households: salaried vs irregular income
        income_volatility = float(rng.uniform(0.03, 0.35))

        population.append({
            "id": i,
            "profile": FinancialProfile(income, expenses, existing_emi, savings),
            "scenario": LoanScenario(f"loan_{i}", principal, rate, tenure),
            "income_volatility": income_volatility,
        })

    return population


def run_population_study(
    population: list[dict], n_trials: int = 2000, seed: int = 42
) -> list[dict]:
    """Evaluate, score, and simulate every member of the population."""
    rows = []

    for member in population:
        evaluation = evaluate_scenario(member["profile"], member["scenario"])
        score = borrowing_stress_score(evaluation)

        assumptions = SimulationAssumptions(
            n_trials=n_trials,
            seed=seed,
            income_volatility=member["income_volatility"],
        )
        simulation = simulate_scenario(
            member["profile"], evaluation["total_emi"], assumptions
        )

        rows.append({
            "id": member["id"],
            "income": member["profile"].monthly_income,
            "income_volatility": member["income_volatility"],
            "debt_to_income": evaluation["debt_to_income"],
            "emergency_fund_months": evaluation["emergency_fund_months"],
            "savings_rate": evaluation["savings_rate"],
            "stress_score": score["stress_score"],
            "p_savings_depleted": simulation["p_savings_depleted"],
            "mean_negative_months": simulation["mean_negative_months"],
        })

    return rows